### PR TITLE
Initial version of a GenAI game called 'Guess the Sketch'

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Review by zaratsian — APPROVED** [review]
LGTM. Cool idea and a fun way to integrate into our backend genai services. 

By default, this service deployed as a Cluster IP. I had to port forward so that I could connect to the UI for testing. My only suggestion would be to add an additional instruction at the end of the README stating the options the user has for connecting to the game app UI.

I ran this code when connecting to this app, so maybe you could include this or something along these lines:

`bash
kubectl port-forward svc/guess-the-sketch-app 8080:5000
`

**Comment by roberthbailey** [comment]
> By default, this service deployed as a Cluster IP.

Correct. The next iteration will use Agones, where we will get node IP+port and the servers can be reached externally (assuming you follow the Agones installation instructions and open the proper firewall).

**Comment by zaratsian** [comment]
@roberthbailey, got it! That's perfect.

**Comment by roberthbailey** [comment]
That being said, I just pushed an update to the README so that at least for this version we have the port-forward instructions (I used those as well).

**Pull request merged**
